services:
  db:
    image: mysql:8.0.27
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DbPass}"
      MYSQL_DATABASE: "${DbName}"
      MYSQL_USER: "${DbUser}"
      MYSQL_PASSWORD: "${DbPass}"
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 3000M